create table public.intent_logs (
  id bigint generated by default as identity primary key,
  intent text not null,
  reply text not null,
  robot_action text not null,
  created_at timestamptz not null default now()
);

create index intent_logs_created_at_idx on public.intent_logs (created_at desc);
